In [6]:
import word2vec

In [7]:
word2vec.word2phrase('./text8', './text8-phrases', verbose=True)

Starting training using file ./text8
Words processed: 17000K     Vocab size: 4399K  
Vocab size (unigrams + bigrams): 2419827
Words in train file: 17005206


In [8]:
word2vec.word2vec('./text8-phrases', './text8.bin',size=100, verbose=True)

Starting training using file ./text8-phrases
Vocab size: 98331
Words in train file: 15857306


Alpha:

Alpha: 0.000002  Progress: 100.03%  Words/thread/sec: 258.07k  a: 0.000787  Progress: 96.86%  Words/thread/sec: 257.79k    Words/thread/sec: 257.72k  49%  Words/thread/sec: 257.88k  

In [9]:
word2vec.word2clusters('./text8', 'text8-clusters.txt', 100, verbose=True)

Starting training using file ./text8
Vocab size: 71291
Words in train file: 16718843


Alpha: 0.003863  Progress: 84.62%  Words/thread/sec: 2

Alpha: 0.000002  Progress: 100.03%  Words/thread/sec: 267.53k  rds/thread/sec: 267.86k  ogress: 85.48%  Words/thread/sec: 267.84k  pha: 0.003531  Progress: 85.89%  Words/thread/sec: 268.02k  /thread/sec: 267.99k  ss: 86.89%  Words/thread/sec: 267.89k   ords/thread/sec: 267.94k  2823  Progress: 88.72%  Words/thread/sec: 267.94k  ec: 267.97k  s: 89.93%  Words/thread/sec: 267.94k  rds/thread/sec: 267.67k  064  Progress: 91.76%  Words/thread/sec: 267.83k  c: 267.89k  : 92.96%  Words/thread/sec: 267.83k  ds/thread/sec: 267.63k  06  Progress: 94.79%  Words/thread/sec: 267.71k  : 267.69k   96.00%  Words/thread/sec: 267.62k  lpha: 0.000850  Progress: 96.61%  Words/thread/sec: 267.57k  s/thread/sec: 267.51k  6  Progress: 97.83%  Words/thread/sec: 267.48k  ead/sec: 267.41k  ogress: 99.27%  Words/thread/sec: 267.51k  50k  

In [10]:
model = word2vec.load('./text8.bin')

In [11]:
model.distance("dog", "cat", "fish")

[('dog', 'cat', 0.8757651848202184),
 ('dog', 'fish', 0.576146212617054),
 ('cat', 'fish', 0.6075471967292344)]

In [12]:
model['smart']

array([ 0.10383469, -0.03810332,  0.10694793, -0.07635857,  0.01192249,
        0.00898876,  0.07324234,  0.13108669,  0.03215753,  0.29339385,
        0.09017763,  0.07774335, -0.12340257, -0.14901538, -0.00491548,
        0.25304404,  0.16912441,  0.0418642 , -0.09427869, -0.11164249,
       -0.01351638,  0.10025671,  0.05933226, -0.02902417,  0.07949277,
       -0.05298655, -0.17613231,  0.02685861,  0.16368447,  0.02420704,
       -0.05695096,  0.04067115, -0.00434021,  0.20319873, -0.03105992,
        0.12483331,  0.02873126,  0.10413764, -0.00161448,  0.12126049,
        0.20188434,  0.08547278, -0.20287371, -0.09231057, -0.02627631,
       -0.04817518,  0.05105604, -0.09251729, -0.0307997 ,  0.06902239,
       -0.05298126,  0.17325756, -0.05238661, -0.01418307, -0.04091166,
       -0.18264481,  0.06929308, -0.05004989, -0.1437766 ,  0.07005091,
       -0.05088917, -0.01436506, -0.04813844, -0.0013987 , -0.11721841,
        0.0777441 , -0.01684148, -0.00281684,  0.13080715, -0.12

In [13]:
model.distance("smart", "intelligent")

[('smart', 'intelligent', 0.501432082299897)]

In [14]:
model.distance("intelligent", "smart")

[('intelligent', 'smart', 0.501432082299897)]

In [15]:
model.distance("smart", "smarter")

[('smart', 'smarter', 0.5808234781555707)]

In [16]:
model.distance("smart", "clever")

[('smart', 'clever', 0.6580811169167574)]

In [17]:
model.distance("smart", "genius")

[('smart', 'genius', 0.3177689733442094)]

In [18]:
model.distance("predictable", "capable")

[('predictable', 'capable', 0.3125932738890035)]

In [19]:
model.distance("merciless", "penniless")

[('merciless', 'penniless', 0.5327922426685675)]

In [20]:
model.distance("predictable", "portable")

[('predictable', 'portable', 0.2909192081434649)]

In [21]:
model.distance("merciless", "moneyless")

KeyError: 'moneyless'

In [22]:
model.distance("merciless", "priceless")

[('merciless', 'priceless', 0.45799782720271026)]

In [23]:
model.distance("predictable", "portable")

[('predictable', 'portable', 0.2909192081434649)]

In [24]:
model.distance("merciless", "homeless")

[('merciless', 'homeless', 0.20107688614188196)]

In [25]:
model.distance("merciless", "fearless")

[('merciless', 'fearless', 0.5879441927826895)]

In [26]:
model.distance("merciless", "helpless")

[('merciless', 'helpless', 0.3818820661175661)]

In [27]:
model.distance("predictable", "capable")

[('predictable', 'capable', 0.3125932738890035)]

In [28]:
model.distance("predictable", "adaptable")

[('predictable', 'adaptable', 0.524790256663955)]

In [29]:
model.distance("portable", "adaptable")

[('portable', 'adaptable', 0.5064347763568511)]

In [30]:
indexes, metrics = model.similar("smart")

In [31]:
model.vocab[indexes]

array(['cute', 'dumb', 'lazy', 'hacking', 'talking', 'taggart', 'dirty',
       'backup', 'kids', 'clever'], dtype='<U78')

In [32]:
indexes, metrics = model.similar("smart")

In [33]:
model.generate_response(indexes, metrics)

rec.array([('cute', 0.69646093), ('dumb', 0.68990728),
           ('lazy', 0.68271411), ('hacking', 0.68189179),
           ('talking', 0.6762697 ), ('taggart', 0.67329918),
           ('dirty', 0.66787625), ('backup', 0.66201173),
           ('kids', 0.65968448), ('clever', 0.65808112)],
          dtype=[('word', '<U78'), ('metric', '<f8')])

In [34]:
indexes, metrics = model.similar("dog")
indexes, metrics

(array([ 2437,  5478,  2670, 10309,  7593, 10230,  9963,  9744,  3964,
         2428]),
 array([0.87576518, 0.84227757, 0.76672897, 0.7660271 , 0.76253066,
        0.7598084 , 0.75647424, 0.75472949, 0.75291579, 0.75183957]))

In [35]:
model.generate_response(indexes, metrics)

rec.array([('cat', 0.87576518), ('cow', 0.84227757), ('bird', 0.76672897),
           ('rat', 0.7660271 ), ('goat', 0.76253066), ('pig', 0.7598084 ),
           ('rabbit', 0.75647424), ('hamster', 0.75472949),
           ('dogs', 0.75291579), ('bear', 0.75183957)],
          dtype=[('word', '<U78'), ('metric', '<f8')])

In [36]:
indexes, metrics = model.analogy(pos=['king', 'woman'], neg=['man'])
indexes, metrics

(array([1087, 1145, 7523, 1335,  648, 6768,  344, 3141, 8419, 9504]),
 array([0.28593446, 0.27063314, 0.27039194, 0.26973328, 0.26502973,
        0.26490313, 0.26444308, 0.26294156, 0.26041239, 0.26031817]))

In [37]:
model.generate_response(indexes, metrics).tolist()

[('queen', 0.2859344576479652),
 ('prince', 0.27063313682239065),
 ('empress', 0.2703919371474418),
 ('wife', 0.26973328313537265),
 ('emperor', 0.2650297335263984),
 ('regent', 0.2649031274090863),
 ('son', 0.26444307759691077),
 ('monarch', 0.26294156007641856),
 ('aragon', 0.26041239175013287),
 ('crown_prince', 0.26031817003341484)]

In [38]:
clusters = word2vec.load_clusters('./text8-clusters.txt')

In [39]:
model.clusters = clusters

In [40]:
indexes, metrics = model.analogy(pos=["paris", "germany"], neg=["france"])

In [41]:
model.generate_response(indexes, metrics).tolist()

[('berlin', 0.32593820767968884, 15),
 ('munich', 0.29014661675674336, 21),
 ('vienna', 0.2836317485622388, 12),
 ('moscow', 0.26963188460573884, 74),
 ('leipzig', 0.2682571044531965, 8),
 ('st_petersburg', 0.26349637585896446, 61),
 ('dresden', 0.2521168820841117, 71),
 ('hamburg', 0.24860147001471591, 8),
 ('prague', 0.2474866704624842, 85),
 ('z_rich', 0.24492016604906452, 55)]

In [42]:
indexes, metrics = model.analogy(pos=['king', 'woman'], neg=['man'])

In [43]:
model.generate_response(indexes, metrics).tolist()

[('queen', 0.2859344576479652, 20),
 ('prince', 0.27063313682239065, 14),
 ('empress', 0.2703919371474418, 72),
 ('wife', 0.26973328313537265, 24),
 ('emperor', 0.2650297335263984, 67),
 ('regent', 0.2649031274090863, 11),
 ('son', 0.26444307759691077, 15),
 ('monarch', 0.26294156007641856, 56),
 ('aragon', 0.26041239175013287, 54),
 ('crown_prince', 0.26031817003341484, 6)]

In [44]:
from scipy.stats import pearsonr, spearmanr

In [45]:
import numpy as np

In [46]:
indexes, metrics = model.similar("dog")
indexes, metrics

(array([ 2437,  5478,  2670, 10309,  7593, 10230,  9963,  9744,  3964,
         2428]),
 array([0.87576518, 0.84227757, 0.76672897, 0.7660271 , 0.76253066,
        0.7598084 , 0.75647424, 0.75472949, 0.75291579, 0.75183957]))

In [47]:
model.generate_response(indexes, metrics).tolist()

[('cat', 0.8757651848202183, 12),
 ('cow', 0.8422775733957731, 72),
 ('bird', 0.7667289670751051, 84),
 ('rat', 0.7660270992193063, 46),
 ('goat', 0.7625306602938164, 51),
 ('pig', 0.7598083990187189, 10),
 ('rabbit', 0.7564742431256671, 88),
 ('hamster', 0.7547294916720856, 23),
 ('dogs', 0.7529157851955368, 69),
 ('bear', 0.7518395681667571, 43)]

In [49]:
model

In [50]:
model.embeddings

AttributeError: 'WordVectors' object has no attribute 'embeddings'

In [51]:
model.generate_response(indexes, metrics).tolist()

[('cat', 0.8757651848202183, 12),
 ('cow', 0.8422775733957731, 72),
 ('bird', 0.7667289670751051, 84),
 ('rat', 0.7660270992193063, 46),
 ('goat', 0.7625306602938164, 51),
 ('pig', 0.7598083990187189, 10),
 ('rabbit', 0.7564742431256671, 88),
 ('hamster', 0.7547294916720856, 23),
 ('dogs', 0.7529157851955368, 69),
 ('bear', 0.7518395681667571, 43)]

In [52]:
model.generate_response(indexes, metrics)

rec.array([('cat', 0.87576518, 12), ('cow', 0.84227757, 72),
           ('bird', 0.76672897, 84), ('rat', 0.7660271 , 46),
           ('goat', 0.76253066, 51), ('pig', 0.7598084 , 10),
           ('rabbit', 0.75647424, 88), ('hamster', 0.75472949, 23),
           ('dogs', 0.75291579, 69), ('bear', 0.75183957, 43)],
          dtype=[('word', '<U78'), ('metric', '<f8'), ('cluster', '<i8')])

In [53]:
model.generate_response(indexes, metrics).tolist()[0]

('cat', 0.8757651848202183, 12)

In [54]:
response =model.generate_response(indexes, metrics).tolist()

In [ ]:
pearson = pearsonr(response,emb[1,:])[0]
    spearman = spearmanr(emb[0,:],emb[1,:])[0]